{{- if eq .Values.ingress.className "traefik" -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "sendent-msteams.fullname" . }}-strip-headers
  labels:
    {{- include "sendent-msteams.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Host: ""
      sendent-apiurl: {{ .Values.config.DEFAULT_NEXTCLOUD_URL | quote }}
{{- end }}