apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendent-msteams.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "sendent-msteams.name" . }}
type: Opaque
data:
  MSAPP_PASSWORD: {{ .Values.secret.msAppPassword | b64enc | quote }}