apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sendent-msteams.fullname" . }}-secret
  labels:
    {{- include "sendent-msteams.labels" . | nindent 4 }}
type: Opaque
data:
  MSAPP_PASSWORD: {{ .Values.secret.MSAPP_PASSWORD | b64enc | quote }}